### ISSUE TITLE
how to persist the data?

### ISSUE THREAD

**Issue by oren** [dperson/moinmoin#1]
I am trying to persist the data of my wiki.
I run the follwing commands: 
1. docker create -v /usr/local/share/moin/data --name moinmoindata debian  
2. docker run --name wiki -d --volumes-from moinmoindata dperson/moinmoin  
3. docker run --name web --link wiki:wiki -p 80:80 -p 443:443 -d dperson/nginx -u "wiki:3031;/wiki"

when I go to https://foo.my-laptop.com/wiki i see: 
"ConfigurationError data_dir "/usr/local/share/moin/data" does not exist, or has incorrect ownership or permissions. Make sure the directory and the subdirectory "pages" are owned by the web server and are readable, writable and executable by the web server user and group."
ls -l /usr/local/share/moin => drwxr-xr-x 2 www-data www-data 4.0K Apr 24 01:37 data

any clues?

**Comment by dperson** [comment]
I believe that the issue is that there is a base template of files in data that moinmoin creates, and as your data volume from the base debian image doesn't have them, it's not happy that they are missing.

```
dperson@tundro$ docker run --rm -it dperson/moinmoin bash                                           
root@96a9c7372fab:/# ls /usr/local/share/moin/data
cache  dict  edit-log  event-log  intermap.txt  meta  pages  plugin  user
```

I'd suggest creating your 'moinmoindata' based on dperson/moinmoin, which already has the data directory as a volume, and the correct template files are included. IE:

```
docker create --name moinmoindata dperson/moinmoin
```

The other alternative, if you aren't using CoreOS or docker swarm, is to just use a local directory mounted into the docker container. This method normally has better IO performance, which typically matters more for databases and such, and probably isn't necessary for a wiki. IE:

```
dperson@tundro$ docker run --rm -it -v /srv/moinmoin:/pass dperson/moinmoin bash
root@96a9c7372fab:/# cp -a /usr/local/share/moin/data/* /pass/
root@96a9c7372fab:/# exit
docker run --name wiki -d -v /srv/moinmoin:/usr/local/share/moin/data dperson/moinmoin
```

Hope that you find this useful. Thanks.

**Comment by oren** [comment]
works now! 

based on your instructions that's the commands I had to run:

setup (run only once)

```
docker run --rm -it -v /srv/moinmoin:/pass dperson/moinmoin bash
cp -a /usr/local/share/moin/data/* /pass/
exit
```

run

```
docker run --name wiki -d -v /srv/moinmoin:/usr/local/share/moin/data dperson/moinmoin
docker run --name web --link wiki:wiki -p 80:80 -p 443:443 -d dperson/nginx -u "wiki:3031;/wiki"
```

I am not sure why we need to copy files manually into /pass. i'll try to understand it tonight.
also, do you think it will be valuable to modify the readme, so other users will have a step by step instructions for persisting the data?

Thank you!
